name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: IF2023_Website

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: IF2023_Website
    - run: npm ci
    - run: npm run build --if-present
    - uses: SamKirkland/FTP-Deploy-Action@3.1.2
      with:
        server: "${{secrets.FTP_SERVERNAME}}"
        username: "${{secrets.FTP_USERNAME}}"
        password: "${{secrets.FTP_PASSWORD}}"
        local-dir: "./IF2023_Website/dist"
        server-dir: "./httpdocs"
