name: PR Staging

on:
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: IF2023_Website

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: IF2023_Website
    - run: npm ci
    - run: npm run build --if-present
  deploy:
    - uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: "${{secrets.STAGING_FTP_SERVERNAME}}"
        username: "${{secrets.STAGING_FTP_USERNAME}}"
        password: "${{secrets.STAGING_FTP_PASSWORD}}"
        local-dir: "./IF2023_Website/dist/"
        server-dir: "/httpdocs/${{ github.head_ref || github.run_id }}/"
    - run: echo "deploy url https://${{ github.head_ref || github.run_id }}.${{vars.STAGING_DOMAIN_NAME}}"
  comment:
    - uses: harupy/comment-on-pr@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        filename: comment-template.md
